apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 1h
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 1h
  chart:
    spec:
      chart: ingress-nginx
      version: "4.12.0"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: ingress-nginx
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    controller:
      image:
        tag: "v1.12.0"
      nodeSelector:
        kubernetes.io/arch: amd64
      hostNetwork: false
      hostPort:
        enabled: false
      enableProfiling: false
      service:
        annotations:
          metallb.universe.tf/address-pool: colt-ingress-pool
        loadBalancerIP: 10.82.50.10
      ingressClassResource:
        name: nginx
        enabled: true
        default: true
        controllerValue: "k8s.io/ingress-nginx"
      config:
        proxy-body-size: "0"
      admissionWebhooks:
        enabled: true
