apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - release.yaml
  - pvc-grafana.yaml
  - deployment-proxmox-exporter.yaml
  - deployment-dcgm-exporter.yaml
