apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - nemotron-49b.yaml

images:
  - name: nim-model-image
    newName: nvcr.io/nim/nvidia/llama-3.3-nemotron-super-49b-v1.5
    newTag: latest

patches:
  - path: mixins/gb10-affinity.yaml
    target:
      kind: Deployment
  - path: mixins/model-depot-cache.yaml
    target:
      kind: Deployment
  - path: mixins/nim-engine-base.yaml
    target:
      kind: Deployment
      name: nemotron-49b-haze
