apiVersion: v1
kind: Namespace
metadata:
  name: nim-system
  labels:
    app.kubernetes.io/part-of: colt-inference
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
