apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference-base
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
        accelerator: gb10
        nvidia.com/gpu.present: "true"
      runtimeClassName: nvidia
      hostNetwork: true
      dnsPolicy: Default
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "dedicated"
          operator: "Equal"
          value: "gpu"
          effect: "NoSchedule"
