apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitea-runner-secret
  namespace: gitea
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: colt-vault
    kind: ClusterSecretStore
  target:
    name: gitea-runner-secret
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: secret/data/colt/gitea_runner
        property: token
