apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - storage/local-path-storage.yaml
  - metallb
  - apps/dns
  - ingress
  - vault/vault-auth-rbac.yaml
  - gitea
  - nvidia
  - cert-manager/release.yaml
  - cert-manager/cluster-issuer.yaml
  - harbor
  - apps/inference
  - apps/litellm
  - apps/open-webui
  - apps/ollama
  - apps/monitoring
  - apps/olah
