apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: litellm-secrets
  namespace: litellm
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: colt-vault
    kind: ClusterSecretStore
  target:
    name: litellm-secrets
    creationPolicy: Owner
  data:
    - secretKey: master-key
      remoteRef:
        key: secret/data/colt/litellm/master_key
        property: master_key
    - secretKey: database-url
      remoteRef:
        key: secret/data/colt/litellm/db
        property: database_url
    - secretKey: db-password
      remoteRef:
        key: secret/data/colt/litellm/db
        property: password
    - secretKey: db-user
      remoteRef:
        key: secret/data/colt/litellm/db
        property: username
    - secretKey: db-name
      remoteRef:
        key: secret/data/colt/litellm/db
        property: database
