apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - pvc.yaml
  - configmap.yaml
  - database.yaml
  - redis.yaml
  - registry.yaml
  - core.yaml
  - jobservice.yaml
  - portal.yaml
  - ingress.yaml
