apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: harbor-vault-secret
  namespace: harbor
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: colt-vault
    kind: ClusterSecretStore
  target:
    name: harbor-secret
    creationPolicy: Owner
  data:
    - secretKey: HARBOR_ADMIN_PASSWORD
      remoteRef:
        key: secret/data/colt/harbor
        property: admin_password
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: secret/data/colt/harbor
        property: database_password
    - secretKey: POSTGRESQL_PASSWORD
      remoteRef:
        key: secret/data/colt/harbor
        property: database_password
    - secretKey: POSTGRESQL_POSTGRES_PASSWORD
      remoteRef:
        key: secret/data/colt/harbor
        property: database_password
    - secretKey: SECRET_KEY
      remoteRef:
        key: secret/data/colt/harbor
        property: secret_key
    - secretKey: CORE_SECRET
      remoteRef:
        key: secret/data/colt/harbor
        property: core_secret
    - secretKey: JOBSERVICE_SECRET
      remoteRef:
        key: secret/data/colt/harbor
        property: jobservice_secret
    - secretKey: REGISTRY_HTTP_SECRET
      remoteRef:
        key: secret/data/colt/harbor
        property: registry_http_secret
    - secretKey: REGISTRY_SECRET
      remoteRef:
        key: secret/data/colt/harbor
        property: core_secret
    - secretKey: private_key.pem
      remoteRef:
        key: secret/data/colt/harbor
        property: token_private_key
    - secretKey: root.crt
      remoteRef:
        key: secret/data/colt/harbor
        property: token_public_cert
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ngc-secret
  namespace: harbor
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: colt-vault
    kind: ClusterSecretStore
  target:
    name: ngc-secret
    creationPolicy: Owner
  data:
    - secretKey: NGC_API_KEY
      remoteRef:
        key: secret/data/colt/infra/ngc
        property: api_key
