apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: colt-vault
spec:
  provider:
    vault:
      server: "https://10.82.0.5:8200"
      path: "secret"
      version: "v2"
      caProvider:
        type: ConfigMap
        name: colt-vault-ca
        namespace: external-secrets
        key: ca.crt
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "external-secrets"
          serviceAccountRef:
            name: "external-secrets"
            namespace: "external-secrets"
