apiVersion: v1
kind: ConfigMap
metadata:
  name: colt-vault-ca
  namespace: external-secrets
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIICETCCAbegAwIBAgIUTHcNbWVlnLz81yR2J3/M+cnZNFgwCgYIKoZIzj0EAwIw
    PDETMBEGA1UEAwwKY29sdC12YXVsdDESMBAGA1UECgwJQ2FtcCBDb2x0MREwDwYD
    VQQLDAhTZWN1cml0eTAeFw0yNjA5MDgyMDIyMzJaFw0yODA5MDcyMDIyMzJaMDwx
    EzARBgNVBAMMCmNvbHQtdmF1bHQxEjAQBgNVBAoMCUNhbXAgQ29sdDERMA8GA1UE
    CwwIU2VjdXJpdHkwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAASYPMK6xvA+fLdp
    5hnGjJnTu3dYEDV180Yfh5rU0s56GScOSySFA+vauFYo6jWj/8C/ovvTiapponC4
    zMd4FR48o4GWMIGTMA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcD
    AQYIKwYBBQUHAwIwQwYDVR0RBDwwOocEClIABYcEfwAAAYIKY29sdC12YXVsdIIV
    Y29sdC12YXVsdC5jb2x0LmxvY2Fsgglsb2NhbGhvc3QwHQYDVR0OBBYEFAa0OIcS
    zxnRHL0U0rbGdl1i+R5VMAoGCCqGSM49BAMCA0gAMEUCIQCH93ZLaT9cJz8j0/pO
    kT08DuADwc26zQtswHcsZscpBQIgHI5/QYmNSTW+KR20c3KVebKaG3zNdUEECPy0
    l3XN5F4=
    -----END CERTIFICATE-----
