apiVersion: v1
kind: ConfigMap
metadata:
  name: olah-config
  namespace: model-cache
  labels:
    app: olah
data:
  configs.toml: |
    [basic]
    host = "0.0.0.0"
    port = 8090
    repos-path = "/data/cache"
    cache-size-limit = "15GB"
    cache-clean-strategy = "LRU"
    mirror-scheme = "https"
    mirror-netloc = "olah.colt.chalko.com"
