apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: olah-cache-pvc
  namespace: model-cache
  labels:
    app: olah
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 20Gi
