apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotPolicy
metadata:
  name: gfs-standard-policy
  namespace: kopiur-system
spec:
  repository:
    kind: ClusterRepository
    name: colt-gdrive-repo
  credentialProjection:
    enabled: true
  sources:
    - pvcSelector:
        labelSelector: {}
  retention:
    keepDaily: 14
    keepWeekly: 6
    keepMonthly: 13
    keepAnnual: 1
